export const BEHAVIOR_INTERVALS = {
  IDLE_MIN_MS: 3000,
  IDLE_MAX_MS: 10000,
  WALK_CHANCE: 0.3,
  SLEEP_TRIGGER_HOUR: 23,
  WAKE_HOUR: 7,
  ENERGY_DECAY_PER_MIN: 0.5,
  AFFECTION_GAIN_PER_INTERACT: 1,
}
